apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-cache
  namespace: cortex-cicd
  labels:
    app.kubernetes.io/name: build-cache
    app.kubernetes.io/part-of: cortex-cicd
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple pipeline runs to access cache simultaneously
  resources:
    requests:
      storage: 20Gi  # Larger cache for layer and dependency storage
  storageClassName: local-path  # Use local-path for k3s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependency-cache
  namespace: cortex-cicd
  labels:
    app.kubernetes.io/name: dependency-cache
    app.kubernetes.io/part-of: cortex-cicd
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple pipeline runs to access cache simultaneously
  resources:
    requests:
      storage: 10Gi  # Cache for node_modules, pip packages, go modules
  storageClassName: local-path
