apiVersion: v1
kind: ResourceQuota
metadata:
  name: cortex-cicd-quota
  namespace: cortex-cicd
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    pods: "30"
    services: "20"
    configmaps: "20"
    secrets: "20"
