apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: knowledge-graph-api
  namespace: cortex-knowledge
spec:
  clusterIP: 10.43.175.202
  clusterIPs:
  - 10.43.175.202
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: knowledge-graph-api
  sessionAffinity: None
  type: ClusterIP
