apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  name: knowledge-elasticsearch
  namespace: cortex-knowledge
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: knowledge-elasticsearch
  serviceName: knowledge-elasticsearch
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: knowledge-elasticsearch
        itil-component: infrastructure
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: elasticsearch
                operator: In
                values:
                - 'true'
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: xpack.security.enabled
          value: 'false'
        - name: xpack.security.enrollment.enabled
          value: 'false'
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                # Disable shard allocation
                curl -X PUT "localhost:9200/_cluster/settings" -H 'Content-Type: application/json' -d'
                {
                  "transient": {
                    "cluster.routing.allocation.enable": "none"
                  }
                }'
                # Perform synced flush
                curl -X POST "localhost:9200/_flush/synced"
                sleep 10
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        startupProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data
        - name: tmp
          mountPath: /tmp
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        name: increase-vm-max-map
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: tmp
        emptyDir: {}
      - hostPath:
          path: /var/lib/elasticsearch
          type: Directory
        name: es-data
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
