apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: knowledge-mongodb
  namespace: cortex-knowledge
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: knowledge-mongodb
  sessionAffinity: None
  type: ClusterIP
