apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: knowledge-elasticsearch
  namespace: cortex-knowledge
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: knowledge-elasticsearch
  sessionAffinity: None
  type: ClusterIP
