apiVersion: v1
kind: Service
metadata:
  name: outline
  namespace: cortex-knowledge
  labels:
    app: outline
    component: documentation
spec:
  type: ClusterIP
  selector:
    app: outline
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  sessionAffinity: None
