apiVersion: batch/v1
kind: Job
metadata:
  name: phoenix-db-init
  namespace: cortex-knowledge
  labels:
    app: phoenix
    component: db-init
spec:
  ttlSecondsAfterFinished: 86400  # Clean up after 24 hours
  template:
    metadata:
      labels:
        app: phoenix
        component: db-init
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: db-init
        image: 10.43.170.72:5000/postgres:15-alpine
        command:
        - /bin/sh
        - -c
        - |
          echo "Creating phoenix database if it doesn't exist..."
          PGPASSWORD=postgres psql -h postgres.cortex-system.svc.cluster.local -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'phoenix'" | grep -q 1 || \
          PGPASSWORD=postgres psql -h postgres.cortex-system.svc.cluster.local -U postgres -c "CREATE DATABASE phoenix;"
          echo "Database phoenix is ready"
        env:
        - name: PGPASSWORD
          value: "postgres"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
