apiVersion: v1
kind: Service
metadata:
  name: phoenix
  namespace: cortex-knowledge
  labels:
    app: phoenix
    component: observability
spec:
  type: ClusterIP
  selector:
    app: phoenix
  ports:
  - name: http
    port: 6006
    targetPort: 6006
    protocol: TCP
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
