apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: cortex-knowledge
  labels:
    app: qdrant
    app.kubernetes.io/part-of: cortex
    cortex.ai/layer: "true"
    cortex.ai/burst-enabled: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6333
    targetPort: 6333
    protocol: TCP
    name: http
  - port: 6334
    targetPort: 6334
    protocol: TCP
    name: grpc
  selector:
    app: qdrant
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: cortex-knowledge
  labels:
    app: qdrant
    app.kubernetes.io/part-of: cortex
    cortex.ai/layer: "true"
    cortex.ai/burst-enabled: "true"
  annotations:
    cortex.ai/layer-domain: "knowledge-embeddings"
    cortex.ai/data-purpose: "layer-specific-knowledge-vectors"
spec:
  serviceName: qdrant
  replicas: 1  # TODO: Change to 0 once KEDA is installed
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "6333"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
          protocol: TCP
        - containerPort: 6334
          protocol: TCP
        env:
        - name: QDRANT__SERVICE__HTTP_PORT
          value: "6333"
        - name: QDRANT__SERVICE__GRPC_PORT
          value: "6334"
        - name: QDRANT__LOG_LEVEL
          value: "INFO"
        - name: QDRANT__STORAGE__PERFORMANCE__MAX_OPTIMIZATION_THREADS
          value: "2"
        volumeMounts:
        - name: data
          mountPath: /qdrant/storage
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6333
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6333
          initialDelaySeconds: 30
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        cortex.ai/layer: "true"
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 20Gi
