apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: value-stream-optimizer
  namespace: cortex-knowledge
spec:
  clusterIP: 10.43.210.210
  clusterIPs:
  - 10.43.210.210
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: metrics
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: value-stream-optimizer
  sessionAffinity: None
  type: ClusterIP
