apiVersion: v1
kind: Service
metadata:
  name: layer-discovery
  namespace: cortex-ai-infra
  labels:
    app: layer-discovery
    app.kubernetes.io/part-of: cortex
    cortex.ai/substrate: "true"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: layer-discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer-discovery
  namespace: cortex-ai-infra
  labels:
    app: layer-discovery
    app.kubernetes.io/part-of: cortex
    cortex.ai/substrate: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layer-discovery
  template:
    metadata:
      labels:
        app: layer-discovery
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: layer-discovery
      containers:
      - name: discovery
        image: 10.43.170.72:5000/layer-discovery:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: NAMESPACE_LABEL
          value: "cortex.ai/layer=true"
        - name: BURST_ANNOTATION
          value: "cortex.ai/burst-enabled"
        - name: TELEMETRY_ENDPOINT
          value: "telemetry-collector.cortex-ai-infra.svc.cluster.local:4317"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: layer-discovery
  namespace: cortex-ai-infra
  labels:
    cortex.ai/substrate: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: layer-discovery
  labels:
    cortex.ai/substrate: "true"
rules:
- apiGroups: [""]
  resources: ["namespaces", "services", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: layer-discovery
  labels:
    cortex.ai/substrate: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: layer-discovery
subjects:
- kind: ServiceAccount
  name: layer-discovery
  namespace: cortex-ai-infra
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: layer-discovery-config
  namespace: cortex-ai-infra
  labels:
    cortex.ai/substrate: "true"
data:
  README.md: |
    # Layer Discovery Service

    ## Purpose
    Service mesh coordinator for layer-to-layer communication.

    ## Functions
    - Discover all layers with `cortex.ai/layer=true` label
    - Track burst-enabled services with `cortex.ai/burst-enabled` annotation
    - Provide service endpoints for cross-layer calls
    - Monitor layer health and availability
    - Route telemetry to central collector

    ## API Endpoints
    - GET /layers - List all discovered layers
    - GET /layers/{name} - Get layer details (services, endpoints, health)
    - GET /layers/{name}/telemetry - Get layer telemetry summary
    - GET /health - Health check
    - GET /ready - Readiness check
    - GET /metrics - Prometheus metrics

    ## Usage
    Layers can query this service to discover other layers:
    ```bash
    curl http://layer-discovery.cortex-ai-infra:8080/layers
    ```

    Response:
    ```json
    {
      "layers": [
        {
          "name": "cortex-knowledge",
          "namespace": "cortex-knowledge",
          "burst_enabled": true,
          "services": {
            "moe_router": "moe-router.cortex-knowledge:8080",
            "qdrant": "qdrant.cortex-knowledge:6333",
            "mcp_server": "mcp-server.cortex-knowledge:3000"
          },
          "health": "healthy",
          "samples_collected": 1247,
          "distillation_eligible": false
        }
      ]
    }
    ```
