apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: cortex-ai-infra
  labels:
    app: qdrant
    app.kubernetes.io/part-of: cortex
    cortex.ai/shared-service: "true"
spec:
  type: ClusterIP
  ports:
  - port: 6333
    targetPort: 6333
    protocol: TCP
    name: http
  - port: 6334
    targetPort: 6334
    protocol: TCP
    name: grpc
  selector:
    app: qdrant
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: cortex-ai-infra
  labels:
    app: qdrant
    component: vector-database
    app.kubernetes.io/part-of: cortex
    cortex.ai/shared-service: "true"
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
        component: vector-database
    spec:
      containers:
      - name: qdrant
        image: 10.43.170.72:5000/qdrant:v1.7.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6333
          name: http
          protocol: TCP
        - containerPort: 6334
          name: grpc
          protocol: TCP
        env:
        - name: QDRANT__SERVICE__HTTP_PORT
          value: "6333"
        - name: QDRANT__SERVICE__GRPC_PORT
          value: "6334"
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 6333
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 6333
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: qdrant-storage
        emptyDir:
          sizeLimit: 50Gi
