apiVersion: v1
kind: ResourceQuota
metadata:
  name: cortex-ai-infra-quota
  namespace: cortex-ai-infra
  labels:
    app.kubernetes.io/part-of: cortex
spec:
  hard:
    limits.cpu: "16"
    limits.memory: "32Gi"
    requests.cpu: "4"
    requests.memory: "8Gi"
    persistentvolumeclaims: "5"
    pods: "30"
    services: "10"
    configmaps: "20"
    secrets: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cortex-ai-infra-limits
  namespace: cortex-ai-infra
  labels:
    app.kubernetes.io/part-of: cortex
spec:
  limits:
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "10m"
      memory: "32Mi"
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    maxLimitRequestRatio:
      cpu: 4
      memory: 2
    type: Container
  - max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Pod
