apiVersion: v1
kind: ResourceQuota
metadata:
  name: cortex-ai-infra-quota
  namespace: cortex-ai-infra
  labels:
    app.kubernetes.io/part-of: cortex
    cortex.ai/substrate: "true"
spec:
  hard:
    limits.cpu: "8"
    limits.memory: "16Gi"
    requests.cpu: "2"
    requests.memory: "4Gi"
    persistentvolumeclaims: "3"
    pods: "10"
    services: "5"
    configmaps: "20"
    secrets: "10"
