apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restart-k3s-service
  namespace: registry
  annotations:
    description: "Restarts k3s/k3s-agent service on all nodes to pick up new registries.yaml"
spec:
  selector:
    matchLabels:
      app: restart-k3s-service
  template:
    metadata:
      labels:
        app: restart-k3s-service
    spec:
      hostPID: true
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: restarter
        image: busybox:latest
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          echo "Restarting k3s service on $(cat /host/etc/hostname)..."

          # Use nsenter to run systemctl in the host namespace
          # Try k3s first (for server nodes), then k3s-agent (for worker nodes)
          nsenter -t 1 -m -u -i -n -p -- /bin/sh -c '
            if systemctl is-active k3s >/dev/null 2>&1; then
              echo "Restarting k3s server..."
              systemctl restart k3s
            elif systemctl is-active k3s-agent >/dev/null 2>&1; then
              echo "Restarting k3s-agent..."
              systemctl restart k3s-agent
            else
              echo "Neither k3s nor k3s-agent is active, skipping restart"
            fi
          '

          echo "Done. Sleeping..."
          sleep infinity
        volumeMounts:
        - name: host-etc
          mountPath: /host/etc
          readOnly: true
      volumes:
      - name: host-etc
        hostPath:
          path: /etc
          type: Directory
