apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cortex-school
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cortex-io/cortex-gitops.git
    targetRevision: main
    path: apps/cortex-school
  destination:
    server: https://kubernetes.default.svc
    namespace: cortex-school
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
