apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cortex-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ry-ops/cortex-gitops.git
    targetRevision: main
    path: apps/cortex-system
  destination:
    server: https://kubernetes.default.svc
    namespace: cortex-system
  syncPolicy:
    automated:
      prune: false  # Start with false, enable after validation
      selfHeal: false  # Start with false, enable after validation
    syncOptions:
      - CreateNamespace=false  # Namespace already exists
