apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-collections
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: cortex-qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cortex-qdrant-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: curlimages/curl:8.5.0
          command:
            - /bin/sh
            - -c
            - |
              set -e
              QDRANT_URL="http://{{ .Release.Name }}.{{ .Values.global.namespace }}:6333"
              
              echo "Waiting for Qdrant to be ready..."
              until curl -sf "$QDRANT_URL/readyz"; do
                echo "Qdrant not ready, waiting..."
                sleep 2
              done
              echo "Qdrant is ready!"
              
              {{- range $name, $config := .Values.collections }}
              echo "Creating collection: {{ $name }}"
              curl -sf -X PUT "$QDRANT_URL/collections/{{ $name }}" \
                -H "Content-Type: application/json" \
                -d '{
                  "vectors": {
                    "size": {{ $config.vectorSize }},
                    "distance": "{{ $config.distance }}"
                  },
                  "on_disk_payload": {{ $config.onDiskPayload | default false }}
                }' || echo "Collection {{ $name }} may already exist"
              
              {{- range $config.indexes }}
              echo "Creating index on {{ $name }}.{{ .field }}"
              curl -sf -X PUT "$QDRANT_URL/collections/{{ $name }}/index" \
                -H "Content-Type: application/json" \
                -d '{
                  "field_name": "{{ .field }}",
                  "field_schema": "{{ .type }}"
                }' || echo "Index {{ .field }} may already exist"
              {{- end }}
              
              {{- end }}
              
              echo "All collections initialized!"
