apiVersion: v1
kind: Service
metadata:
  annotations:
    auth.istio.io/8089: NONE
    field.cattle.io/publicEndpoints: '[{"port":31584,"protocol":"TCP","serviceName":"cortex:cm-acme-http-solver-hsgsx","allNodes":true}]'
  generateName: cm-acme-http-solver-
  labels:
    acme.cert-manager.io/http-domain: '1499662338'
    acme.cert-manager.io/http-token: '1074925140'
    acme.cert-manager.io/http01-solver: 'true'
  name: cm-acme-http-solver-hsgsx
  namespace: cortex
  ownerReferences:
  - apiVersion: acme.cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Challenge
    name: cortex-api-tls-1-181336435-531462493
    uid: 361c8780-5e22-4cad-bf47-4fd0d9daa616
spec:
  clusterIP: 10.43.204.106
  clusterIPs:
  - 10.43.204.106
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31584
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    acme.cert-manager.io/http-domain: '1499662338'
    acme.cert-manager.io/http-token: '1074925140'
    acme.cert-manager.io/http01-solver: 'true'
  sessionAffinity: None
  type: NodePort
