apiVersion: batch/v1
kind: Job
metadata:
  name: build-cortex-orchestrator
  namespace: cortex
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: clone-repo
        image: alpine/git:2.43.0
        command:
        - /bin/sh
        - -c
        - |
          TOKEN=$(cat /secret/token)
          git clone --depth 1 --branch main "https://ry-ops:${TOKEN}@github.com/ry-ops/cortex-platform.git" /workspace
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 256Mi
        volumeMounts:
        - name: github-token
          mountPath: /secret
          readOnly: true
        - name: workspace
          mountPath: /workspace
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=Dockerfile"
        - "--context=/workspace/services/mcp-servers/cortex-orchestrator"
        - "--destination=10.43.170.72:5000/cortex-orchestrator:latest"
        - "--insecure"
        - "--skip-tls-verify"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: github-token
        secret:
          secretName: github-token
      - name: workspace
        emptyDir: {}
  backoffLimit: 2
