apiVersion: v1
kind: Service
metadata:
  name: cortex-desktop-mcp
  namespace: cortex
spec:
  ports:
  - name: http
    nodePort: 32021
    port: 8765
    protocol: TCP
    targetPort: 8765
  selector:
    app: cortex-desktop-mcp
  type: NodePort
