apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: documentation-master
  name: documentation-master
  namespace: cortex
spec:
  clusterIP: 10.43.150.170
  clusterIPs:
  - 10.43.150.170
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: documentation-master
  sessionAffinity: None
  type: ClusterIP
