apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cortex-core:/Service:cortex/redis-queue
  labels:
    app: redis-queue
    component: task-queue
  name: redis-queue
  namespace: cortex
spec:
  clusterIP: 10.43.10.63
  clusterIPs:
  - 10.43.10.63
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-queue
  sessionAffinity: None
  type: ClusterIP
