apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: youtube-channel-intelligence
  name: youtube-channel-intelligence
  namespace: cortex
spec:
  clusterIP: 10.43.126.218
  clusterIPs:
  - 10.43.126.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: youtube-channel-intelligence
  sessionAffinity: None
  type: ClusterIP
