apiVersion: v1
kind: Service
metadata:
  name: checkmk
  namespace: checkmk
  labels:
    app: checkmk
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: checkmk
