apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: checkmk
  namespace: checkmk
  labels:
    app: checkmk
spec:
  serviceName: checkmk
  replicas: 1
  selector:
    matchLabels:
      app: checkmk
  template:
    metadata:
      labels:
        app: checkmk
    spec:
      containers:
      - name: checkmk
        image: checkmk/check-mk-raw:2.4.0-latest
        env:
        - name: CMK_PASSWORD
          value: "cortex-admin-password"
        - name: CMK_SITE_ID
          value: "cmk"
        - name: TZ
          value: "America/Chicago"
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        volumeMounts:
        - name: checkmk-data
          mountPath: /omd/sites
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 800m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /cmk/check_mk/login.py
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /cmk/check_mk/login.py
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: checkmk-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: tmp
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
