apiVersion: v1
kind: Service
metadata:
  name: checkmk-mcp-server
  namespace: cortex-system
  labels:
    app: checkmk-mcp-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: checkmk-mcp-server
