apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: cloudflare-mcp-server
  namespace: cortex-system
spec:
  clusterIP: 10.43.183.185
  clusterIPs:
  - 10.43.183.185
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cloudflare-mcp-server
  sessionAffinity: None
  type: ClusterIP
