apiVersion: v1
kind: Service
metadata:
  name: cloudflare-mcp-server
  namespace: cortex-system
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: cloudflare-mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-mcp-server
  namespace: cortex-system
  labels:
    app: cloudflare-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-mcp-server
  template:
    metadata:
      labels:
        app: cloudflare-mcp-server
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        args:
        - clone
        - --single-branch
        - --depth=1
        - https://github.com/ry-ops/cloudflare-mcp-server.git
        - /repo
        volumeMounts:
        - name: repo
          mountPath: /repo
      containers:
      - name: app
        image: python:3.11-slim
        workingDir: /app
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -e
          echo "Installing cloudflare-mcp-server..."
          pip install --no-cache-dir -e /app
          echo "Starting Cloudflare MCP Server with SSE transport on port 3000..."

          # Create HTTP wrapper for JSON-RPC MCP protocol
          cat > /tmp/mcp-wrapper.py << 'WRAPPER_EOF'
          import asyncio
          import json
          import sys
          from aiohttp import web

          # Global MCP process state
          mcp_proc = None
          mcp_lock = asyncio.Lock()
          mcp_initialized = False
          request_counter = 0

          async def start_mcp_process():
              """Start the MCP server process."""
              return await asyncio.create_subprocess_exec(
                  'python', '-m', 'cloudflare_mcp_server',
                  stdin=asyncio.subprocess.PIPE,
                  stdout=asyncio.subprocess.PIPE,
                  stderr=asyncio.subprocess.PIPE
              )

          async def raw_send(proc, request_data):
              """Send request and get response from MCP process."""
              proc.stdin.write((json.dumps(request_data) + '\n').encode())
              await proc.stdin.drain()
              line = await asyncio.wait_for(proc.stdout.readline(), timeout=30.0)
              if line:
                  return json.loads(line.decode())
              return None

          async def ensure_initialized():
              """Ensure MCP process is started and initialized."""
              global mcp_proc, mcp_initialized, request_counter

              if mcp_proc is None or mcp_proc.returncode is not None:
                  mcp_proc = await start_mcp_process()
                  mcp_initialized = False
                  print("[MCP] Started new MCP process", file=sys.stderr, flush=True)

              if not mcp_initialized:
                  request_counter += 1
                  init_request = {
                      "jsonrpc": "2.0",
                      "method": "initialize",
                      "id": request_counter,
                      "params": {
                          "protocolVersion": "2024-11-05",
                          "capabilities": {},
                          "clientInfo": {"name": "cloudflare-wrapper", "version": "1.0.0"}
                      }
                  }
                  response = await raw_send(mcp_proc, init_request)
                  if response and "result" in response:
                      mcp_initialized = True
                      print(f"[MCP] Initialized: {response.get('result', {}).get('serverInfo', {})}", file=sys.stderr, flush=True)
                      # Send initialized notification
                      request_counter += 1
                      await raw_send(mcp_proc, {"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}})
                  else:
                      print(f"[MCP] Init failed: {response}", file=sys.stderr, flush=True)

          async def send_to_mcp(request_data):
              """Send a JSON-RPC request to MCP process and get response."""
              global mcp_proc, mcp_initialized, request_counter

              async with mcp_lock:
                  try:
                      await ensure_initialized()
                      request_counter += 1
                      request_data = dict(request_data)
                      request_data['id'] = request_counter
                      response = await raw_send(mcp_proc, request_data)
                      return response if response else {"error": "No response from MCP server"}
                  except asyncio.TimeoutError:
                      print("[MCP] Request timed out", file=sys.stderr, flush=True)
                      if mcp_proc:
                          mcp_proc.terminate()
                      mcp_proc = None
                      mcp_initialized = False
                      return {"error": "MCP request timed out"}
                  except Exception as e:
                      print(f"[MCP] Error: {e}", file=sys.stderr, flush=True)
                      mcp_proc = None
                      mcp_initialized = False
                      return {"error": str(e)}

          async def handle_jsonrpc(request):
              """Handle JSON-RPC requests."""
              try:
                  data = await request.json()
              except:
                  return web.json_response(
                      {"jsonrpc": "2.0", "error": {"code": -32700, "message": "Parse error"}, "id": None},
                      status=200
                  )

              req_id = data.get("id", 1)
              response = await send_to_mcp(data)

              if response is None:
                  return web.json_response({
                      "jsonrpc": "2.0", "id": req_id,
                      "error": {"code": -32603, "message": "No response"}
                  })

              if "error" in response and not isinstance(response.get("error"), dict):
                  return web.json_response({
                      "jsonrpc": "2.0", "id": req_id,
                      "error": {"code": -32603, "message": response["error"]}
                  })

              return web.json_response(response)

          async def handle_health(request):
              return web.json_response({'status': 'healthy', 'server': 'cloudflare-mcp', 'initialized': mcp_initialized})

          app = web.Application()
          app.router.add_post('/', handle_jsonrpc)
          app.router.add_get('/health', handle_health)

          print("[MCP] Starting Cloudflare MCP wrapper on port 3000", file=sys.stderr, flush=True)
          web.run_app(app, host='0.0.0.0', port=3000)
          WRAPPER_EOF

          pip install aiohttp
          python /tmp/mcp-wrapper.py
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-mcp-secrets
              key: api-token
              optional: true
        - name: CLOUDFLARE_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: cloudflare-mcp-secrets
              key: account-id
              optional: true
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
        volumeMounts:
        - name: repo
          mountPath: /app
      volumes:
      - name: repo
        emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudflare-mcp-ingress
  namespace: cortex-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: cloudflare-mcp.ry-ops.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudflare-mcp-server
            port:
              number: 3000
  tls:
  - hosts:
    - cloudflare-mcp.ry-ops.dev
    secretName: cloudflare-mcp-tls
