apiVersion: v1
kind: Service
metadata:
  annotations:
    auth.istio.io/8089: NONE
    field.cattle.io/publicEndpoints: '[{"port":30557,"protocol":"TCP","serviceName":"cortex-system:cm-acme-http-solver-rs6lx","allNodes":true}]'
  generateName: cm-acme-http-solver-
  labels:
    acme.cert-manager.io/http-domain: '1505101832'
    acme.cert-manager.io/http-token: '1391267707'
    acme.cert-manager.io/http01-solver: 'true'
  name: cm-acme-http-solver-rs6lx
  namespace: cortex-system
  ownerReferences:
  - apiVersion: acme.cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Challenge
    name: cortex-mcp-tls-1-118174447-1464926704
    uid: 1617c1f3-42bc-41e0-a734-0cd42f7afaa7
spec:
  clusterIP: 10.43.239.32
  clusterIPs:
  - 10.43.239.32
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30557
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    acme.cert-manager.io/http-domain: '1505101832'
    acme.cert-manager.io/http-token: '1391267707'
    acme.cert-manager.io/http01-solver: 'true'
  sessionAffinity: None
  type: NodePort
