apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: coordinator-master
  namespace: cortex-system
spec:
  clusterIP: 10.43.123.134
  clusterIPs:
  - 10.43.123.134
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: coordinator-master
  sessionAffinity: None
  type: ClusterIP
