apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: cortex-orchestrator
    component: orchestration
  name: cortex-orchestrator
  namespace: cortex-system
spec:
  clusterIP: 10.43.28.99
  clusterIPs:
  - 10.43.28.99
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mcp
    port: 8080
    protocol: TCP
    targetPort: mcp
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app: cortex-orchestrator
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
