apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: development-master
  namespace: cortex-system
spec:
  clusterIP: 10.43.164.140
  clusterIPs:
  - 10.43.164.140
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: development-master
  sessionAffinity: None
  type: ClusterIP
