apiVersion: v1
kind: Service
metadata:
  name: kubernetes-mcp-server
  namespace: cortex-system
  labels:
    app: kubernetes-mcp-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: kubernetes-mcp-server
