apiVersion: batch/v1
kind: Job
metadata:
  name: build-langflow-chat-mcp
  namespace: cortex-system
spec:
  template:
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
        - sh
        - -c
        - |
          git clone https://github.com/ry-ops/cortex-platform.git /workspace
          cd /workspace/services/mcp-servers/langflow-chat
          ls -la
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=/workspace/services/mcp-servers/langflow-chat"
        - "--dockerfile=/workspace/services/mcp-servers/langflow-chat/Dockerfile"
        - "--destination=10.43.170.72:5000/langflow-chat-mcp-server:latest"
        - "--insecure"
        - "--skip-tls-verify"
        - "--verbosity=info"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: workspace
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 3
