apiVersion: v1
kind: Service
metadata:
  name: langflow-chat-mcp-server
  namespace: cortex-system
  labels:
    app: langflow-chat-mcp-server
    component: mcp-server
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: langflow-chat-mcp-server
