apiVersion: v1
kind: Service
metadata:
  name: n8n-mcp-server
  namespace: cortex-system
  labels:
    app: n8n-mcp-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3002
    targetPort: 3002
    protocol: TCP
  selector:
    app: n8n-mcp-server
