apiVersion: v1
kind: Service
metadata:
  name: outline-mcp-server
  namespace: cortex-system
  labels:
    app: outline-mcp-server
spec:
  type: ClusterIP
  selector:
    app: outline-mcp-server
  ports:
  - name: http
    port: 3004
    targetPort: http
    protocol: TCP
  sessionAffinity: None
