apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: postgres-exporter
  name: postgres-exporter
  namespace: cortex-system
spec:
  clusterIP: 10.43.208.2
  clusterIPs:
  - 10.43.208.2
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9187
    protocol: TCP
    targetPort: 9187
  selector:
    app: postgres-exporter
  sessionAffinity: None
  type: ClusterIP
