apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cortex-system:/Service:cortex-system/redis-replicas
    meta.helm.sh/release-name: redis
    meta.helm.sh/release-namespace: cortex-system
  labels:
    app.kubernetes.io/component: replica
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 8.4.0
    helm.sh/chart: redis-24.1.0
  name: redis-replicas
  namespace: cortex-system
spec:
  clusterIP: 10.43.134.95
  clusterIPs:
  - 10.43.134.95
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/component: replica
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: ClusterIP
