apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: redis
    component: chat-persistence
  name: redis
  namespace: cortex-system
spec:
  clusterIP: 10.43.214.90
  clusterIPs:
  - 10.43.214.90
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
