apiVersion: v1
kind: ResourceQuota
metadata:
  name: cortex-system-quota
  namespace: cortex-system
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    pods: "100"
    services: "50"
    configmaps: "60"
    secrets: "50"
