apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cortex-system:/Service:cortex-system/sandfly-mcp-server
  labels:
    app: sandfly-mcp-server
  name: sandfly-mcp-server
  namespace: cortex-system
spec:
  clusterIP: 10.43.143.53
  clusterIPs:
  - 10.43.143.53
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sandfly-mcp-server
  sessionAffinity: None
  type: ClusterIP
