apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: security-master
  namespace: cortex-system
spec:
  clusterIP: 10.43.173.115
  clusterIPs:
  - 10.43.173.115
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: security-master
  sessionAffinity: None
  type: ClusterIP
