apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: unifi-mcp-server
  namespace: cortex-system
spec:
  clusterIP: 10.43.178.37
  clusterIPs:
  - 10.43.178.37
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: unifi-mcp-server
  sessionAffinity: None
  type: ClusterIP
