apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: redis
    cortex.ai/component: security-monitoring
  name: redis
  namespace: cortex-security
spec:
  clusterIP: 10.43.57.150
  clusterIPs:
  - 10.43.57.150
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
