apiVersion: v1
kind: ResourceQuota
metadata:
  name: cortex-security-quota
  namespace: cortex-security
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "10"
    pods: "40"
    services: "30"
    configmaps: "30"
    secrets: "30"
