apiVersion: batch/v1
kind: Job
metadata:
  name: csaf-seed-apps-loader
  namespace: cortex-csaf
spec:
  template:
    metadata:
      labels:
        app: seed-apps-loader
    spec:
      restartPolicy: OnFailure
      containers:
        - name: loader
          image: python:3.11-slim
          command:
            - /bin/bash
            - -c
            - |
              pip install --quiet pyyaml requests

              cat > /tmp/loader.py << 'EOF'
              import os
              import yaml
              import json
              import requests
              import time

              REGISTRY_URL = "http://csaf-registry:8080"

              print("Waiting for registry to be ready...")
              time.sleep(30)

              for filename in os.listdir('/apps'):
                  if filename.endswith('.yaml'):
                      filepath = os.path.join('/apps', filename)
                      print(f"Loading app: {filename}")

                      with open(filepath, 'r') as f:
                          app_definition = yaml.safe_load(f)

                      try:
                          response = requests.post(
                              f"{REGISTRY_URL}/api/apps",
                              json=app_definition,
                              headers={"Content-Type": "application/json"}
                          )
                          response.raise_for_status()
                          print(f"  ✓ Loaded {app_definition['metadata']['name']}")
                      except Exception as e:
                          print(f"  ✗ Failed to load {filename}: {e}")
                      time.sleep(2)

              print("Seed apps loading complete")
              EOF

              python /tmp/loader.py
          volumeMounts:
            - name: seed-apps
              mountPath: /apps
      volumes:
        - name: seed-apps
          configMap:
            name: csaf-seed-apps
