apiVersion: v1
kind: Service
metadata:
  name: csaf-postgres
  namespace: cortex-csaf
spec:
  selector:
    app: csaf-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None  # Headless service for StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: csaf-postgres
  namespace: cortex-csaf
spec:
  serviceName: csaf-postgres
  replicas: 1
  selector:
    matchLabels:
      app: csaf-postgres
  template:
    metadata:
      labels:
        app: csaf-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: "csaf"
            - name: POSTGRES_PASSWORD
              value: "csaf-password-change-me"
            - name: POSTGRES_DB
              value: "csaf"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - csaf
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - csaf
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
