apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-moe-chat-router-v6
  namespace: cortex-chat
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: setup-git-credentials
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          TOKEN=$(cat /secret/token)
          mkdir -p /root
          echo "https://ry-ops:${TOKEN}@github.com" > /root/.git-credentials
          chmod 600 /root/.git-credentials
          echo "[credential]" > /root/.gitconfig
          echo "    helper = store" >> /root/.gitconfig
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: github-token
          mountPath: /secret
          readOnly: true
        - name: git-home
          mountPath: /root
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=Dockerfile.simple"
        - "--context=https://github.com/ry-ops/cortex-platform.git#refs/heads/main:/services/moe-router"
        - "--destination=10.43.170.72:5000/moe-router:latest"
        - "--insecure"
        - "--skip-tls-verify"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1Gi
        volumeMounts:
        - name: git-home
          mountPath: /root
      volumes:
      - name: github-token
        secret:
          secretName: github-token
      - name: git-home
        emptyDir: {}
