apiVersion: v1
kind: ConfigMap
metadata:
  name: moe-router-chat-api-build
  namespace: cortex-chat
data:
  Dockerfile: |
    FROM python:3.11-slim
    WORKDIR /app
    RUN pip install --no-cache-dir flask==3.0.0 flask-cors==4.0.0 anthropic==0.50.0 requests==2.31.0
    RUN cat > /app/app.py <<'PYTHON_EOF'
    #!/usr/bin/env python3
    import os
    import logging
    from flask import Flask, request, jsonify
    from flask_cors import CORS
    from anthropic import Anthropic

    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)

    app = Flask(__name__)
    CORS(app)

    api_key = os.getenv('ANTHROPIC_API_KEY')
    anthropic_client = Anthropic(api_key=api_key) if api_key else None
    conversations = {}

    @app.route('/health', methods=['GET'])
    def health():
        return jsonify({"status": "healthy", "service": "simple-chat-api", "anthropic_configured": anthropic_client is not None}), 200

    @app.route('/api/auth/login', methods=['POST'])
    def login():
        data = request.json or {}
        username = data.get('username', 'user')
        return jsonify({"token": "mock-token-123", "user": {"username": username, "id": "user-1"}}), 200

    @app.route('/api/conversations', methods=['GET'])
    def get_conversations():
        conv_list = [{"id": cid, "title": f"Conversation {cid}", "lastMessage": msgs[-1]["content"] if msgs else "No messages", "timestamp": "2026-01-19T00:00:00Z"} for cid, msgs in conversations.items()]
        return jsonify(conv_list), 200

    @app.route('/api/conversations', methods=['POST'])
    def create_conversation():
        conv_id = f"conv-{len(conversations) + 1}"
        conversations[conv_id] = []
        return jsonify({"id": conv_id, "title": f"New Conversation {conv_id}"}), 201

    @app.route('/api/chat', methods=['POST'])
    def chat():
        try:
            data = request.json
            message = data.get('message', '')
            conversation_id = data.get('conversation_id', 'default')
            if conversation_id not in conversations:
                conversations[conversation_id] = []
            conversations[conversation_id].append({"role": "user", "content": message})
            if anthropic_client:
                try:
                    response = anthropic_client.messages.create(model="claude-sonnet-4-20250514", max_tokens=1024, messages=conversations[conversation_id])
                    assistant_message = response.content[0].text
                except Exception as e:
                    assistant_message = f"Error: {str(e)}"
            else:
                assistant_message = f"Echo: {message}"
            conversations[conversation_id].append({"role": "assistant", "content": assistant_message})
            return jsonify({"response": assistant_message, "conversation_id": conversation_id, "expert": "general", "timestamp": "2026-01-19T00:00:00Z"}), 200
        except Exception as e:
            return jsonify({"error": str(e)}), 500

    @app.route('/api/conversations/<conversation_id>/messages', methods=['GET'])
    def get_messages(conversation_id):
        if conversation_id not in conversations:
            return jsonify([]), 200
        messages = [{"role": msg["role"], "content": msg["content"], "timestamp": "2026-01-19T00:00:00Z"} for msg in conversations[conversation_id]]
        return jsonify(messages), 200

    if __name__ == '__main__':
        logger.info("Starting Simple Chat API on http://0.0.0.0:8080")
        app.run(host='0.0.0.0', port=8080, debug=False)
    PYTHON_EOF
    RUN chmod +x /app/app.py
    USER 1000
    EXPOSE 8080
    CMD ["python", "/app/app.py"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: build-moe-chat-api
  namespace: cortex-chat
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=/workspace/Dockerfile"
        - "--context=dir:///workspace"
        - "--destination=10.43.170.72:5000/moe-router:latest"
        - "--insecure"
        - "--skip-tls-verify"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1Gi
        volumeMounts:
        - name: build-context
          mountPath: /workspace
      volumes:
      - name: build-context
        configMap:
          name: moe-router-chat-api-build
