apiVersion: v1
kind: ConfigMap
metadata:
  name: moe-router-chat-api-build
  namespace: cortex-chat
data:
  Dockerfile: |
    FROM python:3.11-slim
    WORKDIR /app
    RUN pip install --no-cache-dir flask==3.0.0 flask-cors==4.0.0 anthropic==0.50.0 requests==2.31.0
    RUN printf '#!/usr/bin/env python3\nimport os, logging\nfrom flask import Flask, request, jsonify\nfrom flask_cors import CORS\nfrom anthropic import Anthropic\n\nlogging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")\nlogger = logging.getLogger(__name__)\napp = Flask(__name__)\nCORS(app)\napi_key = os.getenv("ANTHROPIC_API_KEY")\nanthropic_client = Anthropic(api_key=api_key) if api_key else None\nconversations = {}\n\n@app.route("/health", methods=["GET"])\ndef health():\n    return jsonify({"status": "healthy", "service": "simple-chat-api", "anthropic_configured": anthropic_client is not None}), 200\n\n@app.route("/api/auth/login", methods=["POST"])\ndef login():\n    data = request.json or {}\n    username = data.get("username", "user")\n    return jsonify({"token": "mock-token-123", "user": {"username": username, "id": "user-1"}}), 200\n\n@app.route("/api/conversations", methods=["GET"])\ndef get_conversations():\n    conv_list = [{"id": cid, "title": f"Conversation {cid}", "lastMessage": msgs[-1]["content"] if msgs else "No messages", "timestamp": "2026-01-19T00:00:00Z"} for cid, msgs in conversations.items()]\n    return jsonify(conv_list), 200\n\n@app.route("/api/conversations", methods=["POST"])\ndef create_conversation():\n    conv_id = f"conv-{len(conversations) + 1}"\n    conversations[conv_id] = []\n    return jsonify({"id": conv_id, "title": f"New Conversation {conv_id}"}), 201\n\n@app.route("/api/chat", methods=["POST"])\ndef chat():\n    try:\n        data = request.json\n        message = data.get("message", "")\n        conversation_id = data.get("conversation_id", "default")\n        if conversation_id not in conversations:\n            conversations[conversation_id] = []\n        conversations[conversation_id].append({"role": "user", "content": message})\n        if anthropic_client:\n            try:\n                response = anthropic_client.messages.create(model="claude-sonnet-4-20250514", max_tokens=1024, messages=conversations[conversation_id])\n                assistant_message = response.content[0].text\n            except Exception as e:\n                assistant_message = f"Error: {str(e)}"\n        else:\n            assistant_message = f"Echo: {message}"\n        conversations[conversation_id].append({"role": "assistant", "content": assistant_message})\n        return jsonify({"response": assistant_message, "conversation_id": conversation_id, "expert": "general", "timestamp": "2026-01-19T00:00:00Z"}), 200\n    except Exception as e:\n        return jsonify({"error": str(e)}), 500\n\n@app.route("/api/conversations/<conversation_id>/messages", methods=["GET"])\ndef get_messages(conversation_id):\n    if conversation_id not in conversations:\n        return jsonify([]), 200\n    messages = [{"role": msg["role"], "content": msg["content"], "timestamp": "2026-01-19T00:00:00Z"} for msg in conversations[conversation_id]]\n    return jsonify(messages), 200\n\nif __name__ == "__main__":\n    logger.info("Starting Simple Chat API on http://0.0.0.0:8080")\n    logger.info(f"Anthropic API configured: {anthropic_client is not None}")\n    app.run(host="0.0.0.0", port=8080, debug=False)\n' > app.py
    RUN chmod +x /app/app.py
    USER 1000
    EXPOSE 8080
    CMD ["python", "/app/app.py"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: build-moe-chat-api
  namespace: cortex-chat
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=/workspace/Dockerfile"
        - "--context=dir:///workspace"
        - "--destination=10.43.170.72:5000/moe-router:latest"
        - "--insecure"
        - "--skip-tls-verify"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1Gi
        volumeMounts:
        - name: build-context
          mountPath: /workspace
      volumes:
      - name: build-context
        configMap:
          name: moe-router-chat-api-build
