apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-moe-chat-router-v3
  namespace: cortex-chat
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: setup-git-credentials
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          TOKEN=$(cat /secret/token)
          echo "https://ry-ops:${TOKEN}@github.com" > /kaniko/.git-credentials
          chmod 600 /kaniko/.git-credentials
        volumeMounts:
        - name: github-token
          mountPath: /secret
          readOnly: true
        - name: git-credentials
          mountPath: /kaniko
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=Dockerfile.simple"
        - "--context=git://github.com/ry-ops/cortex-platform.git#refs/heads/main:/services/moe-router"
        - "--destination=10.43.170.72:5000/moe-router:latest"
        - "--insecure"
        - "--skip-tls-verify"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1Gi
        volumeMounts:
        - name: git-credentials
          mountPath: /kaniko/.git-credentials
          subPath: .git-credentials
      volumes:
      - name: github-token
        secret:
          secretName: github-token
      - name: git-credentials
        emptyDir: {}
