apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cortex-chat
spec:
  type: NodePort
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 32379
  selector:
    app: redis
  sessionAffinity: None
