apiVersion: v1
kind: ResourceQuota
metadata:
  name: cortex-chat-quota
  namespace: cortex-chat
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 10Gi
    limits.cpu: "10"
    limits.memory: 20Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "30"
    configmaps: "30"
    secrets: "30"
