apiVersion: v1
kind: LimitRange
metadata:
  name: cortex-dev-limits
  namespace: cortex-dev
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    min:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: 4
      memory: 8Gi
    maxLimitRequestRatio:
      cpu: 4
      memory: 2
  - type: Pod
    max:
      cpu: 8
      memory: 16Gi
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 100Gi
