apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-pdb
  namespace: cortex-dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis
  unhealthyPodEvictionPolicy: IfHealthyBudget
