apiVersion: v1
kind: ResourceQuota
metadata:
  name: cortex-dev-quota
  namespace: cortex-dev
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "30"
    configmaps: "30"
    secrets: "30"
